language: php

php:
  - '7.3'
  - '7.4'

services:
  - redis
  - redis-server
  
before_script:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml